// ==============================================================================
// ☕ RADAR LOYALTY ENGINE — COMPREHENSIVE DEMO STORE SEED & RESET ENGINE
// Provides a complete, ready-to-test Demo Store (Menu, Modifiers, Staff, Services, Customers)
// With an instant 1-click Reset mechanism back to pristine state.
// ==============================================================================

import {
  Store,
  StoreStaff,
  Customer,
  Tier,
  Privilege,
  CatalogItem,
  StoreSpecialist,
  StoreWallet,
  CustomerCoupon,
  AuditLog,
} from '../types';

export const DEMO_STORE_ID = 'demo-cafe-store-uuid';
export const DEMO_STORE_SLUG = 'demo-cafe';

export const INITIAL_DEMO_STORE: Store = {
  id: DEMO_STORE_ID,
  slug: DEMO_STORE_SLUG,
  name: 'رادار كافيه التجريبي (Demo Cafe)',
  logo_url: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=400&auto=format&fit=crop&q=80',
  primary_color: '#0F172A',
  secondary_color: '#F59E0B',
  points_per_riyal: 1.0,
  subscription_active: true,
  status: 'active',
  subscription_status: 'active',
  subscription_plan: 'pro',
  setup_fee_paid: true,
  manager_name: 'مدير المتجر التجريبي',
  manager_contact: '0550000000',
  custom_domain: null,
  welcome_gift_type: 'POINTS',
  welcome_points: 50,
  welcome_offer_title: 'قهوة اليوم مجاناً مع أول زيارة',
  slider_images: [
    {
      id: 'demo-slide-1',
      image_url: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&auto=format&fit=crop&q=80',
      title: 'قهوة مختصة محضرة بشغف ☕',
      quote: 'اجمع نقاطك واستمتع بمكافآتك مع كل رشفة',
      badge_text: 'عضوية رادار',
    },
    {
      id: 'demo-slide-2',
      image_url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&auto=format&fit=crop&q=80',
      title: 'حلا وكيك طازج يومياً 🍰',
      quote: 'استبدل نقاطك بألذ الحلويات والمشروبات الحصرية',
      badge_text: 'مكافآت حصرية',
    },
  ],
  is_demo: true,
  catalog_enabled: true,
  created_at: '2026-01-01T00:00:00.000Z',
  updated_at: new Date().toISOString(),
};

export const INITIAL_DEMO_TIERS: Tier[] = [
  {
    id: 'tier-demo-1',
    store_id: DEMO_STORE_ID,
    tier_name: 'ضيف (Guest)',
    required_xp: 0,
    badge_color: '#94A3B8',
    created_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'tier-demo-2',
    store_id: DEMO_STORE_ID,
    tier_name: 'برونزي (Bronze)',
    required_xp: 150,
    badge_color: '#CD7F32',
    created_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'tier-demo-3',
    store_id: DEMO_STORE_ID,
    tier_name: 'فضي (Silver)',
    required_xp: 500,
    badge_color: '#3B82F6',
    created_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'tier-demo-4',
    store_id: DEMO_STORE_ID,
    tier_name: 'VIP Gold 👑',
    required_xp: 1200,
    badge_color: '#F59E0B',
    created_at: '2026-01-01T00:00:00.000Z',
  },
];

export const INITIAL_DEMO_PRIVILEGES: Privilege[] = [
  {
    id: 'priv-demo-1',
    store_id: DEMO_STORE_ID,
    required_tier_id: 'tier-demo-1',
    title: 'قهوة اليوم مجانية (Black Coffee)',
    description: 'استمتع بكوب قهوة يوم طازجة ومحضرة من أجود حبوب البن',
    image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400&auto=format&fit=crop&q=80',
    cost_points: 50,
    quantity_limit: 100,
    per_customer_limit: 2,
    redeemed_count: 5,
    valid_start_time: '00:00',
    valid_end_time: '23:59',
    is_active: true,
    is_hidden: false,
    created_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'priv-demo-2',
    store_id: DEMO_STORE_ID,
    required_tier_id: 'tier-demo-2',
    title: 'خصم 25% على الفاتورة الكاملة',
    description: 'خصم خاص وحصري لأعضاء المستوى البرونزي فما فوق',
    image_url: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=400&auto=format&fit=crop&q=80',
    cost_points: 100,
    quantity_limit: 50,
    per_customer_limit: 1,
    redeemed_count: 12,
    valid_start_time: '00:00',
    valid_end_time: '23:59',
    is_active: true,
    is_hidden: false,
    created_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'priv-demo-3',
    store_id: DEMO_STORE_ID,
    required_tier_id: 'tier-demo-3',
    title: 'كيكة سان سباستيان مجاناً 🍰',
    description: 'قطعة حلا سان سباستيان الفاخرة مع صوص الشوكولاتة البلجيكية',
    image_url: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&auto=format&fit=crop&q=80',
    cost_points: 150,
    quantity_limit: 30,
    per_customer_limit: 1,
    redeemed_count: 8,
    valid_start_time: '00:00',
    valid_end_time: '23:59',
    is_active: true,
    is_hidden: false,
    created_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'priv-demo-4',
    store_id: DEMO_STORE_ID,
    required_tier_id: 'tier-demo-4',
    title: 'جلسة خاصة VIP مع مشروبين مجاناً 💎',
    description: 'حجز قاعة الاجتماعات أو الجلسة الخاصة مع ضيافة فاخرة لأعضاء VIP',
    image_url: 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=400&auto=format&fit=crop&q=80',
    cost_points: 300,
    quantity_limit: 10,
    per_customer_limit: 1,
    redeemed_count: 2,
    valid_start_time: '10:00',
    valid_end_time: '22:00',
    is_active: true,
    is_hidden: false,
    created_at: '2026-01-01T00:00:00.000Z',
  },
];

export const INITIAL_DEMO_STAFF: StoreStaff[] = [
  {
    id: 'staff-demo-admin',
    store_id: DEMO_STORE_ID,
    name: 'سعد المنصور (مدير المتجر)',
    phone: '0550000000',
    role: 'admin',
    pin_code: '9999',
    is_active: true,
    can_manual_input_phone: true,
    created_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'staff-demo-cashier',
    store_id: DEMO_STORE_ID,
    name: 'فهد السالم (كاشير نقاط البيع)',
    phone: '0551111111',
    role: 'cashier',
    pin_code: '1234',
    is_active: true,
    can_manual_input_phone: true,
    created_at: '2026-01-01T00:00:00.000Z',
  },
];

export const INITIAL_DEMO_CUSTOMERS: Customer[] = [
  {
    id: 'cust-demo-1',
    store_id: DEMO_STORE_ID,
    phone: '0501112233',
    name: 'سارة العبدالله',
    wallet_balance: 180,
    lifetime_xp: 220,
    last_visit_date: new Date().toISOString(),
    is_demo: true,
    created_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cust-demo-2',
    store_id: DEMO_STORE_ID,
    phone: '0504445566',
    name: 'خالد الدوسري (عميل ذهبي)',
    wallet_balance: 550,
    lifetime_xp: 850,
    last_visit_date: new Date().toISOString(),
    is_demo: true,
    created_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cust-demo-3',
    store_id: DEMO_STORE_ID,
    phone: '0507778899',
    name: 'نورة الشمري (عضو جديد)',
    wallet_balance: 50,
    lifetime_xp: 50,
    last_visit_date: new Date().toISOString(),
    is_demo: true,
    created_at: '2026-01-01T00:00:00.000Z',
  },
];

export const INITIAL_DEMO_CATALOG_ITEMS: CatalogItem[] = [
  {
    id: 'cat-demo-1',
    store_id: DEMO_STORE_ID,
    category: 'مشروبات ساخنة',
    name: 'فلات وايت (Flat White)',
    description: 'دبل شوت إسبريسو مع حليب مبخر برغوة مخملية ناعمة',
    price: 18.0,
    item_type: 'product',
    image_url: 'https://images.unsplash.com/photo-1577968897966-3d4325b36b61?w=400&auto=format&fit=crop&q=80',
    is_available: true,
    modifier_groups: [
      {
        id: 'mod-demo-milk',
        name: 'نوع الحليب',
        title: 'اختر نوع الحليب',
        min_select: 0,
        max_select: 1,
        required: false,
        allow_multiple: false,
        options: [
          { id: 'opt-oat', name: 'حليب شوفان', price_delta: 3 },
          { id: 'opt-almond', name: 'حليب لوز', price_delta: 4 },
          { id: 'opt-coconut', name: 'حليب جوز هند', price_delta: 4 },
        ],
      },
      {
        id: 'mod-demo-shots',
        name: 'إضافات',
        title: 'إضافات على المشروب',
        min_select: 0,
        max_select: 3,
        required: false,
        allow_multiple: true,
        options: [
          { id: 'opt-extra-shot', name: 'شوت إسبريسو إضافي', price_delta: 4 },
          { id: 'opt-syrup-vanilla', name: 'سيروب فانيليا', price_delta: 3 },
          { id: 'opt-syrup-caramel', name: 'سيروب كراميل مملح', price_delta: 3 },
        ],
      },
    ],
    created_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cat-demo-2',
    store_id: DEMO_STORE_ID,
    category: 'مشروبات باردة',
    name: 'آيس سبانش لاتيه (Iced Spanish)',
    description: 'مزيج القهوة الغنية مع الحليب المحلى والثلج المنعش',
    price: 22.0,
    item_type: 'product',
    image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=400&auto=format&fit=crop&q=80',
    is_available: true,
    created_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cat-demo-3',
    store_id: DEMO_STORE_ID,
    category: 'مشروبات ساخنة',
    name: 'كولومبيا V60 مقطرة',
    description: 'محصول كولومبي مختص بإيحاءات الفواكه والشوكولاتة',
    price: 20.0,
    item_type: 'product',
    image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400&auto=format&fit=crop&q=80',
    is_available: true,
    created_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cat-demo-4',
    store_id: DEMO_STORE_ID,
    category: 'حلويات',
    name: 'كيكة العسل الملكية',
    description: 'طبقات البسكويت الهش مع كريمة العسل الطبيعي',
    price: 26.0,
    item_type: 'product',
    image_url: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&auto=format&fit=crop&q=80',
    is_available: true,
    created_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'cat-demo-5',
    store_id: DEMO_STORE_ID,
    category: 'ساندوتشات',
    name: 'كرواسون حلومي مشوي مع الزعتر',
    description: 'كرواسون فرنسي طازج محشو بجبن الحلوم المشوي والطماطم المجففة',
    price: 19.0,
    item_type: 'product',
    image_url: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=400&auto=format&fit=crop&q=80',
    is_available: true,
    created_at: '2026-01-01T00:00:00.000Z',
  },
];

export const INITIAL_DEMO_SPECIALISTS: StoreSpecialist[] = [
  {
    id: 'spec-demo-1',
    store_id: DEMO_STORE_ID,
    name: 'سعد القحطاني',
    specialty: 'كبير الباريستا وخبير القهوة المختصة',
    phone: '0552223344',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    service_categories: ['مشروبات ساخنة', 'مشروبات باردة'],
    working_days: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Sat'],
    working_hours: { start: '08:00', end: '16:00' },
    is_active: true,
    created_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'spec-demo-2',
    store_id: DEMO_STORE_ID,
    name: 'أحمد العلي',
    specialty: 'أخصائي التحميص وحلويات القهوة',
    phone: '0554445566',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    service_categories: ['حلويات', 'مشروبات ساخنة'],
    working_days: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    working_hours: { start: '16:00', end: '00:00' },
    is_active: true,
    created_at: '2026-01-01T00:00:00.000Z',
  },
];

export const INITIAL_DEMO_WALLET: StoreWallet = {
  id: 'wallet-demo-cafe',
  store_id: DEMO_STORE_ID,
  sms_quota: 1000,
  sms_used: 12,
  wa_quota: 500,
  wa_used: 28,
  cashier_limit: 5,
  extra_cashiers_purchased: 3,
  whatsapp_provider: 'direct',
  created_at: '2026-01-01T00:00:00.000Z',
};

export const INITIAL_DEMO_COUPONS: CustomerCoupon[] = [
  {
    id: 'coupon-demo-1',
    coupon_code: 'CAFE-DEMO-789',
    customer_id: 'cust-demo-1',
    customer_phone: '0501112233',
    customer_name: 'سارة العبدالله',
    store_id: DEMO_STORE_ID,
    privilege_id: 'priv-demo-1',
    privilege_title: 'قهوة اليوم مجانية (Black Coffee)',
    cost_points: 50,
    status: 'ACTIVE',
    valid_start_time: '00:00',
    valid_end_time: '23:59',
    purchased_at: new Date().toISOString(),
  },
];

export const INITIAL_DEMO_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-demo-1',
    store_id: DEMO_STORE_ID,
    staff_id: 'staff-demo-cashier',
    customer_id: 'cust-demo-1',
    customer_phone: '0501112233',
    customer_name: 'سارة العبدالله',
    action: 'PURCHASE',
    purchase_amount: 45.0,
    points_changed: 45,
    entry_method: 'qr_scan',
    is_demo: true,
    metadata: { note: 'نقاط مشتريات (POS)' },
    created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'log-demo-2',
    store_id: DEMO_STORE_ID,
    staff_id: 'staff-demo-cashier',
    customer_id: 'cust-demo-2',
    customer_phone: '0504445566',
    customer_name: 'خالد الدوسري',
    action: 'REDEEM_COUPON',
    purchase_amount: 0,
    points_changed: -100,
    entry_method: 'qr_scan',
    is_demo: true,
    metadata: { coupon_code: 'DEMO25', note: 'استبدال مكافأة خصم 25%' },
    created_at: new Date(Date.now() - 3600000 * 5).toISOString(),
  },
];
